  
APP_VER: "01.00"
ATTRIBUTE: 0
ATTRIBUTE2: 0
ATTRIBUTE_MINOR: 0x11
CATEGORY: gd
CONTENT_ID: HB0000-SVMP00001_00-0000000000000000
PARENTAL_LEVEL: 1
PSP2_DISP_VER: "03.600"
PSP2_SYSTEM_VER: 0x03600000
SAVEDATA_MAX_SIZE: 0x100000
STITLE: Vita Media Player
TITLE: Vita Media Player
TITLE_ID: SVMP00001
VERSION: "01.00"